### ISSUE TITLE
add support - "Flickr" is overflowing

### ISSUE THREAD

**Issue by spidgorny** [spidgorny/concert-log#10]
when adding a support, is it possible to make the boxes (under the picture) a bit less large so they fit properly on screen ? (on my screen the last textbox "Flickr" is overflowing)
(see Picture 2)

**Comment by spidgorny** [comment]
will make the buttons vertical in the support popup (or make the popup wider, but it will not help for smaller phones)

**Comment by Reaperdaddy** [comment]
fixed for me
