### ISSUE TITLE
red screen of death when support does not have a photo

### ISSUE THREAD

**Issue by spidgorny** [spidgorny/concert-log#11]
i experienced a weird bug but it can be reproduced:
When creating or modifying a concert, if you go to add a support but dont select a picture and directly touch the arrow on the top left to go back to the previous screen, it create a bug with a red screen of death.... (see Picture 3)

**Comment by spidgorny** [comment]
![screenshot](https://scontent-frx5-1.xx.fbcdn.net/v/t1.15752-9/50748251_295095864535302_4897975851045355520_n.png?_nc_cat=111&_nc_ht=scontent-frx5-1.xx&oh=0e92275972c96cf2a014d0a864032d5d&oe=5CBF946A)

**Comment by Reaperdaddy** [comment]
fixed for me
