### ISSUE TITLE
list view vertical image overflow

### ISSUE THREAD

**Issue by spidgorny** [spidgorny/concert-log#12]
when using a main concert picture which is higher than larger, the picture will be overflowing the box while looking at the full concerts list
(see Picture 1)

**Comment by spidgorny** [comment]
![screenshot](https://scontent-frx5-1.xx.fbcdn.net/v/t1.15752-9/51090912_296271034404551_3517310187989893120_n.png?_nc_cat=106&_nc_ht=scontent-frx5-1.xx&oh=af0cdf7320d2b5bcebb0fe41f40ad623&oe=5CF8F288)

**Comment by Reaperdaddy** [comment]
fixed for me
