### ISSUE TITLE
adding a support band is confusing when the keyboard is open

### ISSUE THREAD

**Issue by spidgorny** [spidgorny/concert-log#14]
when first arriving on the pop up window for adding a support band, the first thing the user see is just a part of the grey box for the support band picture, and it looks a bit strange to see no text on screen or indications that the user should scroll down to see any text or options ...
(see picture 5)

**Comment by spidgorny** [comment]
![screenshot](https://scontent-frx5-1.xx.fbcdn.net/v/t1.15752-9/50844759_1863513993770744_8688271209726476288_n.png?_nc_cat=105&_nc_ht=scontent-frx5-1.xx&oh=391bd3792e23f473e46cb77cf5f0899d&oe=5CFA07F6)

**Comment by spidgorny** [comment]
hmmm, what would you suggest?

**Comment by Reaperdaddy** [comment]
maybe reorganizing the order of the elements...
On top the field to enter the band name
Under it the stars rating system
And under the picture selection ...
Possible like that maybe ?
Or greatly reducing the size of the grey empty picture box (when not containing a band) ?

**Comment by spidgorny** [comment]
I've removed the gray placeholder completely. And moved the stars up.

**Comment by Reaperdaddy** [comment]
fixed for me
