### ISSUE TITLE
no delete button

### ISSUE THREAD

**Issue by spidgorny** [spidgorny/concert-log#16]
as far as i saw, it is not possible to delete an entry... i made two empty entries in the list as a test, and both cannot be deleted... Is it possible to add a "delete concert" option ?
(see Picture 4)

**Comment by spidgorny** [comment]
![screenshot](https://scontent-frx5-1.xx.fbcdn.net/v/t1.15752-9/50886372_456174818254340_3388590915776937984_n.png?_nc_cat=106&_nc_ht=scontent-frx5-1.xx&oh=275b5836db517df177f9ed4999ad5e52&oe=5CB706D5)

**Comment by spidgorny** [comment]
we will have a delete button on the details page at the top.
should we have a confirmation yes/no?

**Comment by Reaperdaddy** [comment]
yes please add a confirmation screen before deleting an entry

**Comment by Reaperdaddy** [comment]
fixed for me
