### ISSUE TITLE
Onboarding screen is confusing

### ISSUE THREAD

**Issue by spidgorny** [spidgorny/concert-log#18]
Says to press (+) but there is no button there.

**Comment by spidgorny** [comment]
I think we should add a screenshot there. Can you prepare images for me?

**Comment by Reaperdaddy** [comment]
sorrz for no feedback zesterdaz, but zeah, i still somehow think that only one boarding screen would be enough if in the end we dont have much to say on it...

**Comment by spidgorny** [comment]
Removed second on boarding page.
