### ISSUE TITLE
image placeholder

### ISSUE THREAD

**Issue by Reaperdaddy** [spidgorny/concert-log#27]
so...
it seems the previous placeholder was causing some issues but now after selecting a picture for the concert, its not appearing at all, the picture cannot be seen while editing the concert.
Is it possible to solve this and have the picture displayed ? maybe having a much smaller placeholder when empty and that can display full picture when selected ?

**Comment by spidgorny** [comment]
I've tested this and the picture is shown AFTER it's selected from the Photo Library. I've tested the camera as well. Flickr isn't working - true.

**Comment by Reaperdaddy** [comment]
any possibility to have the flickr option working too ?

**Comment by spidgorny** [comment]
Notice the green "fixed" label above? It's fixed.
Once you get a new version - could you go over all fixed issues and close them?
If I were to close them when I think they are fixed - you will have no chance to double-check.

**Comment by Reaperdaddy** [comment]
how do i close an issue ? i already looked for that option and i dont see how to....
And im not sure what you mean by "fixed" in this case... You mean "fixed" like = it will work in the next version , or "fixed"= gallery and camera works but not flickr and it will stay like that ?
