### ISSUE TITLE
test app not saving any data

### ISSUE THREAD

**Issue by spidgorny** [spidgorny/concert-log#7]
it doesnt seem to save at all any new entry... When creating new entries, they appear properly in the list while the user stays in the app. Then after leaving the app and coming back in, all new entries are not saved...
(tried 4 times, in none of the cases the new entries were saved)

**Comment by spidgorny** [comment]
this is because it's a demo version with a hard-coded list of concerts which are static. consider this fixed.

**Comment by Reaperdaddy** [comment]
fixed for me
