### ISSUE TITLE
flickr unnecessary?

### ISSUE THREAD

**Issue by spidgorny** [spidgorny/concert-log#8]
we can totally remove the Flickr option, not needed since not many people except "photo artists" are hosting their pics on flickr

**Comment by spidgorny** [comment]
selecting images from the internet is tricky (see #9), therefore Flickr is a compromise for the time being.
please close the issue if you agree.

**Comment by Reaperdaddy** [comment]
see #9

**Comment by spidgorny** [comment]
We discuss this issue in #9 so I will close this issue.
