### ISSUE TITLE
pick a picture from the internet

### ISSUE THREAD

**Issue by spidgorny** [spidgorny/concert-log#9]
add an option to be able to pick a picture from the internet instead of the flickr option since this is the method most people will use

**Comment by spidgorny** [comment]
Two options: 
- it will search for the band name in Google Image Search and show the results for user to pick.
- it will allow user to copy/paste the image URL found elsewhere.

Option 1: I don't like it because we had many issues with it in the original version of the app. Google has changed their API from public to private (I had to adjust). Once private, we have to register our app and have trouble again when they change the API again.

Option 2: Can be done easily, but not user friendly. Therefore I've made a Flickr image picker.

Feedback needed.

**Comment by Reaperdaddy** [comment]
hi slawa
so... if this is really too complicated to make the selection via internet , then let just have the option to let the user select it from his own handy gallery. The user will have to go on internet by himself to find a picture, but this is not dramatic...
Im am not convinced at all by the utility of the flickr option. I have often used apps that let user upload pictures for whatever reasons, and flickr was never an option as a source... Flickr is really something for photographer and people dont upload normal internet random picture there, just the pics they are proud of.
For info, im a using a mp3 player which has a VERY efficient picture association function. For 80% of my bands, it finds the correct picture for the album + for the artist. If the picture selected automatically is not the good one, the user is connected to an alternative search engine via the app that is also very efficent. If you want to have a look at the app, it is called PlayerPro:
https://play.google.com/store/apps/details?id=com.tbig.playerprotrial
(for me, a system like that would be PERFECT)

**Comment by Reaperdaddy** [comment]
for the moment we can leave it, its not dramatic. I made a few tests and the results are mixed... Its workingt properly if the band is quite famous, but as soon as we enter some bands which are not in magazines or on the radio, then the results are dropping dramatically to 0 good results...
But yeah, if no better solution at the moment, it can stay.

**Comment by spidgorny** [comment]
Player Pro has it's job easier - they search for both the band name and album. This gives them 99% chance of success, because every album has an artwork.
The words of the band name (unless unique) may constitute a normal phrase. Searching for a normal phrase may present a non-music results.

I had trouble with google image search in the past and would like to avoid it. I also understand that Flickr is not the best choice. Given that I have implemented Flickr already it would be unwise to remove it.

> The user will have to go on internet by himself to find a picture, but this is not dramatic...
This is already possible, just download an image to your Downloads folder and then you can select it in the app [First button].

We may consider to implement Google Image search in the next version. My priority is on low hanging rotten fruits - fix the obvious bugs and crashes. Deal with improvements later. OK?

**Comment by Reaperdaddy** [comment]
ok for now on the picture selection topic
